schema: grade10-planning
promoted_by: "@htonyl"
created: 2026-09-24
depends_on:
  - add-shipping-insurance-order-summary-tooltip
hands:
  pm: "@jeffffej0909"
  dev: "@htonyl"
reviewed:
  user-journeys: 9dea7618
  ui-design: 1d453217
