#!/usr/bin/env node
/*
 * BUILD: canonical tokens.json -> theme.css + themes/*.css.
 *
 * tokens.json is the source of truth (designer-owned token DATA). This script
 * applies the engineer-owned PROJECTION rules from tokens.config.json (preamble,
 * shadcn slotMap, per-theme selector) to emit CSS. It is the code-side build of
 * the 2-way pipeline:  tokens:pull (Figma->json) -> tokens:build (json->css).
 *
 * Token identity is the normalized CSS name (e.g. "slate-950", "layer-01").
 * Refs are written {name} in json and become var(--name) here. slotMap values
 * are full Figma names and are normalized the same way the pull step named them.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(
  await readFile(resolve(pkgDir, "tokens.config.json"), "utf8"),
);
const doc = JSON.parse(await readFile(resolve(pkgDir, "tokens.json"), "utf8"));

// Figma variable name -> CSS custom property (same rule the pull step uses to key tokens.json).
const cssVar = (name) => {
  let n = name;
  if (/^color\//i.test(n)) n = n.slice("color/".length);
  else if (n.includes("/")) n = n.slice(n.indexOf("/") + 1);
  return (
    "--" +
    n
      .replace(/[/\s]+/g, "-")
      .replace(/[^a-zA-Z0-9-]/g, "")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
      .toLowerCase()
  );
};
// canonical $value -> CSS value: "{ref}" -> var(--ref); literal passes through.
const cssValue = (v) => v.replace(/^\{([\w-]+)\}$/, "var(--$1)");
// A token's $description rides along as a trailing comment. Collapsed to one
// line and stripped of "*/" so a stray sequence can't terminate the comment.
const note = (desc) =>
  desc
    ? ` /* ${desc.replace(/\s+/g, " ").replace(/\*\//g, "*\\/").trim()} */`
    : "";
const line = (key, val, desc) => `  --${key}: ${cssValue(val)};${note(desc)}`;

const banner = (title, from) =>
  `/* ⚠️  GENERATED by scripts/build-css.mjs — ${title}. Do not edit by hand.\n * Source of truth: ${from}. Edit tokens there (or via tokens:pull from Figma), then run tokens:build. */\n`;

// ── theme.css: preamble + shared primitives ────────────────────────────────
// drop the preamble file's own leading doc comment — it documents the source file, not the output
const preamble = (
  await readFile(resolve(pkgDir, cfg.preamble), "utf8")
).replace(/^\/\*[\s\S]*?\*\/\n/, "");
const primLines = Object.entries(doc.primitives).map(([k, t]) =>
  line(k, t.$value, t.$description),
);
await writeFile(
  resolve(pkgDir, cfg.contractOut),
  `${banner("contract + shared primitives", "tokens.json (primitives)")}\n${preamble}\n/* Primitives — shared, mode-independent */\n:root {\n${primLines.join("\n")}\n}\n`,
  "utf8",
);

// ── themes/<name>.css: raw semantic set + mapped shadcn slots ───────────────
const slotMap = cfg.slotMap ?? {};
// A slot may point at a primitive rather than a theme token — theme.css defines
// primitives on :root, so var() resolves either way from inside a theme block.
// Without this, moving a token from Semantic to Foundation silently emits
// "/* unmapped */" and the slot loses its value.
const primitiveKeys = new Set(Object.keys(doc.primitives));
for (const [name, themeCfg] of Object.entries(cfg.themes)) {
  const theme = doc.themes?.[name];
  if (!theme) {
    console.warn(
      `⚠  theme "${name}" in config but not in tokens.json — skipped`,
    );
    continue;
  }
  const selector = Object.values(themeCfg.modes)[0];
  const keys = new Set(Object.keys(theme.tokens));

  const raw = Object.entries(theme.tokens).map(([k, t]) =>
    line(k, t.$value, t.$description),
  );
  const slots = Object.entries(slotMap).flatMap(([slot, figmaToken]) => {
    const ref = cssVar(figmaToken); // "--text-primary"
    const name = ref.slice(2);
    if (!keys.has(name) && !primitiveKeys.has(name))
      return [`  ${slot}: /* unmapped: ${figmaToken} */;`];
    if (ref === slot) return []; // raw section already defines this exact slot
    return [`  ${slot}: var(${ref});`];
  });
  const block = `${selector} {\n  /* Figma semantic set (raw) */\n${raw.join("\n")}\n\n  /* shadcn contract slots (mapped) */\n${slots.join("\n")}\n}`;
  await writeFile(
    resolve(pkgDir, themeCfg.out),
    `${banner(`${name} theme`, `tokens.json (themes.${name})`)}\n${block}\n`,
    "utf8",
  );
}

console.log(
  `✓ ${Object.keys(doc.primitives).length} primitives -> ${cfg.contractOut}`,
);
for (const name of Object.keys(cfg.themes))
  if (doc.themes?.[name])
    console.log(
      `✓ ${Object.keys(doc.themes[name].tokens).length} semantic + ${Object.keys(slotMap).length} slots -> ${cfg.themes[name].out}`,
    );
