schema: grade10-planning
promoted_by: "@htonyl"
created: 2026-09-21
hands:
  pm: "@jeffffej0909"
  design: "@tangconst"
  tech: "@htonyl"
  qa: "@chloe9gag"
  dev: "@htonyl"
depends_on:
  - redesign-store-product-detail-page
