"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _store_product_card from "./store-product-card.bones.json";

configureBoneyard({
  color: "#E6E6E6",
  darkColor: "rgba(249, 250, 250, 0.05)",
  animate: "pulse",
  transition: 300,
});

registerBones({
  "store-product-card": _store_product_card,
});
