"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _store_cart_amount from "./store-cart-amount.bones.json";
import _store_cart_amount_lg from "./store-cart-amount-lg.bones.json";
import _store_cart_badge from "./store-cart-badge.bones.json";
import _store_cart_item from "./store-cart-item.bones.json";
import _store_product_card from "./store-product-card.bones.json";

configureBoneyard({
  color: "#E6E6E6",
  darkColor: "rgba(249, 250, 250, 0.05)",
  animate: "pulse",
  transition: 300,
});

registerBones({
  "store-cart-amount": _store_cart_amount,
  "store-cart-amount-lg": _store_cart_amount_lg,
  "store-cart-badge": _store_cart_badge,
  "store-cart-item": _store_cart_item,
  "store-product-card": _store_product_card,
});
